default:
  tags:
    - epsec-gitlab

image: docker-registry-remote.artifactory-fpark1.int.net.nokia.com/hashicorp/terraform:1.2.1

variables:
  DEPLOY_INFO: "deployment_info.txt"

stages:
  - create-customer-config
  - publish-to-db
  - clean-up

before_script:
  - apk update
# Install python/pip
  - apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
  - apk add py3-pip
  - python3 -m ensurepip
  - pip install -r requirements.txt

create-customer-config:
  stage: create-customer-config
  script:
    - echo 'RowKey = "ak-cicd"' >> $DEPLOY_INFO
    - echo 'PartitionKey = "ak-cicdpk"' >> $DEPLOY_INFO
  artifacts:
    paths:
      - $DEPLOY_INFO
    expire_in: 7 days

publish-to-db:
  stage: publish-to-db
  needs: [create-customer-config]
  script:
    - python table_api.py publish "$CONN_STR_DB" "$TABLE_NAME" "$DEPLOY_INFO"

clean-up-db:
  stage: clean-up
  needs: [create-customer-config, publish-to-db]
  script:
    - python table_api.py delete "$CONN_STR_DB" "$TABLE_NAME" "$DEPLOY_INFO"
  rules:
    - when: manual
